### ISSUE TITLE
[TODO]

### ISSUE THREAD

**Issue by TheKillerTacos** [PocketProjects/PocketPanel#7]
#Todo

- [x] Main homepage similar to a landing page
- [ ]  The whole login/register system. (save/gets details from the sql. The infos should be located at the /protected/config.php)
- [ ] Installation script so users can install the panel for the first time! Should save the user mysql detials along with the admin user on the config.php ..ect) 
- [ ] user management system where admins can make other users admins! ..ect) 
- [ ] code the panel.php that echo 's a messageg after the user is LOGGED in. (basic)
- No this isn't it. There are still a long TODO list. Those are just the basics for now]!
.

**Comment by SkygridRex** [comment]
- [] use materialize Framework

**Comment by SkygridRex** [comment]
@TheKillerTacos He sido baneado de ClearSky :yum:

**Comment by AndreTheGamer** [comment]
@SkygridRex  ¿Por qué lol?

**Comment by SkygridRex** [comment]
Because i want it

**Comment by TheKillerTacos** [comment]
haha

**Comment by TheKillerTacos** [comment]
Closing, TODO will be soon remade
